CREATE TABLE `gp_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `market_time` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '时间',
  `gp_code` varchar(20) DEFAULT NULL COMMENT '股票CODE',
  `gp_name` varchar(40) DEFAULT NULL COMMENT '股票名称',
  `latest_price` decimal(8,2) DEFAULT NULL COMMENT '最新价',
  `rise_fall_rang` bigint DEFAULT NULL COMMENT '涨跌幅',
  `rise_fall_amount` decimal(8,2) DEFAULT NULL COMMENT '涨跌额',
  `turnover` decimal(15,2) DEFAULT NULL COMMENT '成交量',
  `transaction_volume` decimal(15,2) DEFAULT NULL COMMENT '成交额',
  `amplitude` bigint DEFAULT NULL COMMENT '振幅',
  `highest_price` decimal(10,2) DEFAULT NULL COMMENT '最高',
  `minimum_price` decimal(10,2) DEFAULT NULL COMMENT '最低',
  `today_open_price` decimal(10,2) DEFAULT NULL COMMENT '今开',
  `yesterday_close_price` decimal(10,2) DEFAULT NULL COMMENT '昨收',
  `equivalent_ratio` decimal(10,2) DEFAULT NULL COMMENT '量比',
  `turnover_rate` decimal(10,2) DEFAULT NULL COMMENT '换手率',
  `pe_ratio_movement` decimal(10,2) DEFAULT NULL COMMENT '市赢率-动态',
  `pe_ratio` decimal(10,2) DEFAULT NULL COMMENT '市赢率',
  `total_market_value` decimal(10,2) DEFAULT NULL COMMENT '总市值',
  `circulate_market_value` decimal(10,2) DEFAULT NULL COMMENT '流通市值',
  `speed_increase` decimal(10,2) DEFAULT NULL COMMENT '涨速',
  `five_speed_increase` decimal(10,2) DEFAULT NULL COMMENT '5分钟涨速%',
  `sixty_day_speed_increase` decimal(10,2) DEFAULT NULL COMMENT '60日内涨速%',
  `year_to_date_speed_increase` decimal(10,2) DEFAULT NULL COMMENT '年初至今涨跌幅%',
  `bug_in` decimal(8,2) DEFAULT NULL COMMENT '买入',
  `sell_out` decimal(8,2) DEFAULT NULL COMMENT '卖出',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `index_market_time` (`market_time`),
  KEY `index_gp_code` (`gp_code`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;